name: fluam_app
description: A flarum (flarum.org) application, Seamlessly uses all the flarum sites you add.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # some ICON
  font_awesome_flutter: ^9.2.0
  # http io
  http: ^0.13.4
  # html decoder
  html: ^0.15.0
  # show site start level
  flutter_rating_bar: ^4.0.0
  # for save conf
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  # for get App path
  path_provider: ^2.0.9
  # for use some crypto encoder
  crypto: ^3.0.1
  # for windows
  win32: ^2.4.1
  # for desktop
  waterfall_flow: ^3.0.2
  ffi: ^1.1.2
  # for open_url


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.2
  build_runner: ^2.1.7
  msix: ^3.1.3
flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
flutter_intl:
  enabled: true

msix_config:
  display_name: Fluam
  publisher_display_name: XkeyC Studio
  identity_name: cn.xkeyc.fluam
  msix_version: 1.0.0.0
  certificate_path: ./windows/CERTIFICATE.pfx
  publisher: 'E=me@xkeyc.cn, CN=xkeyc, OU=xkeyc.cn, O=XkeyC Studio, L=BeiJing, S=BeiJing, C=CN'
  logo_path: assets/icon.png
  start_menu_icon_path: assets/icon.png
  tile_icon_path: assets/icon.png
  #vs_generated_images_folder_path: ./assets_windows
  icons_background_color: transparent
  architecture: x64
  capabilities: 'internetClient,location'